import { Component, OnInit, ViewChild  } from '@angular/core';
import { PriceModel, PriceGroupModel } from '../model/PriceModel';
import { GridOptions} from 'ag-grid/main';


@Component({
  selector: "app-pricedetail",
  templateUrl: "./pricedetail.component.html",
  styleUrls: ["./pricedetail.component.css"]
})
export class PricedetailComponent implements OnInit {
  public priceListGroup: PriceGroupModel[];
  public priceList: PriceModel[];

  // ag-grid
  private gridApi;
  private gridColumnApi;
  private getNodeChildDetails;
  private detailCellRendererParams;
  columnDefs;

  constructor() {
    this.columnDefs = [
      {
        headerName: "Loja",
        field: "StoreGroup",
        width: 100,
        enableValue: true,
        cellRenderer: "agGroupCellRenderer"
      },
      {
        headerName: "Boleto",
        //field: "PriceFirstRow.BilletPrice",
        width: 150,
        valueGetter: function(params) {
          debugger
          return  params.data.PriceFirstRow != undefined? params.data.PriceFirstRow.BilletPrice: params.data.BilletPrice;
        }
      },
      {
        headerName: "Cartão Outros",
        children: [
          {
            headerName: "Preço de",
            field: "PriceFirstRow.Price",
            width: 90,
            minwidth: 75,
            maxWidth: 100
          },
          {
            headerName: "Preço por",
            field: "PriceFirstRow.PriceFrom",
            width: 120
          },
          {
            headerName: "Parcelamento sem juros",
            field: "age",
            width: 90
          },
          {
            headerName: "Parcelamento com juros",
            field: "age",
            width: 90
          }
        ]
      },
      {
        headerName: "Cartão Próprio",
        children: [
          {
            headerName: "Preço",
            field: "age",
            width: 120
          },
          {
            headerName: "Parcelamento sem juros",
            field: "age",
            width: 90
          },
          {
            headerName: "Parcelamento com juros",
            field: "age",
            width: 90
          }
        ]
      }
    ];
    // desativado!
    this.getNodeChildDetails = function getNodeChildDetails(rowItem) {
      if (rowItem.StoreGroup) {
        return {
          group: true,
          //expanded: rowItem.StoreGroup === "extra",
          children: rowItem.priceListGroup,
          key: rowItem.StoreGroup,
        };
      } else {
        return null;
      }
    };
  }

  ngOnInit() {
    this.getPrice();
  }

  getPrice(): PriceGroupModel[] {
    this.priceList = [];
    for (let index = 1; index < 20; index++) {
      this.priceList.push(
        new PriceModel(
          index,
          this.rndStore(),
          this.rndSellerName(),
          this.getRDNPrice(),
          this.getRDNPrice(),
          this.getRDNPrice(),
          this.getRDNPrice(),
          this.getI(),
          this.getRDNPrice(),
          1.2,
          this.getRDNPrice(),
          this.getI(),
          this.getRDNPrice(),
          this.getRDNPrice(),
          this.getI(),
          this.getRDNPrice(),
          1.9,
          this.getRDNPrice(),
          this.getI(),
          this.getRDNPrice(),
          new Date()
        )
      );
    }

    const groups = this.priceList.reduce(function(obj, item) {
      obj[item.StoreName] = obj[item.StoreName] || [];
      obj[item.StoreName].push(item);
      return obj;
    }, {});

    const myArray = Object.keys(groups).map(function(key) {
      return {
        StoreGroup: key,
        PriceFirstRow: groups[key][0],
        priceListGroup: groups[key]
      };
    });

    this.priceListGroup = myArray;
    console.log(this.priceListGroup);
    return this.priceListGroup;
  }

  onGridReady(params) {
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;
    params.api.sizeColumnsToFit();

  }



















  getRDNPrice() {
    return (Math.floor(Math.random() * 15000 + 1));
  }
  getI() {
    return Math.floor(Math.random() * 14 + 1);
  }
  rndStore() {
    let stores = [
      "Extra",
      "CasasBahia",
      "PontoFrio",
      "Americanas",
      "Submarino",
      "WallMart",
      "RicardoEletro"
    ];
    return stores[Math.floor(Math.random() * stores.length)];
  }

  rndSellerName():string {
    let stores = [
      "Extra",
      "Casa do vídeo",
      "CasasBahia",
      "PontoFrio",
      "ZTOYSTORE",
      "ZMOCKSHOP LTDA",
      "BEBESTORE",
      "Microsoft",
      "Loja HP",
      "Loja Fuji",
      "GIMBA",
      "MEUAMIGOPET",
      "PEDALA",
      "JOCAR",
      "UZGAMES",
      "WOLLOKO",
      "CAMERUM",
      "QUECOZINHA",
      "IPHONESHOPPING",
      "MEUSACESSORIOSAPPLE",
      "OPCOESTELEFONES",
      "MONSTROCELULAR",
      "CASAAMERICA",
      "WEBFONES",
      "EXTRADELIVERY",
      "FORMADECRIAR",
      "MUSICALBRASIL",
      "OBOTOPESCAESPORTIVA",
      "SHOPLUXO",
      "Casas Bahia",
      "STORECOURO",
      "EOTICA",
      "ETERNAJOIA",
      "PIPPERJOIAS",
      "CELSITE",
      "MUNDOCONCEPT",
      "LOUCASPORACESSORIOS",
      "BABYOU",
      "JOIASBRASIL",
      "SHOPFISIO",
      "PETCOMPRE",
      "ESPORTEBRASIL",
      "WCARE",
      "INDIESHOP",
      "Mega Colchões",
      "ELENS",
      "BOOCKERS",
      "Cooktampa",
      "CASACLIMA",
      "OFFICETOTALSHOP",
      "MARCYN",
      "SOSUPLEMENTOS",
      "PNEUSTORE",
      "STOKY",
      "PLAYTECH",
      "POLISHOP",
      "SANDROMOSCOLONI",
      "SOFACAMAFUTON",
      "CHICEELEGANTE",
      "SAUDEJA",
      "ITARO",
      "POLARIO",
      "PADMINIINCENSOS",
      "BAZARHORIZONTE",
      "SOFTWARESTORE",
      "BETTERSOLUTIONS",
      "ELLASTORE",
      "DOURAL",
      "FABRICA9",
      "Livraria Mundo da Leitura",
      "DÓKE",
      "DOMGATO",
      "TODOLIVRO",
      "Delgrani",
      "Farmácia Doce Vida",
      "Overboard",
      "Eclock",
      "Kola",
      "MegaMamute",
      "Complete O Carro",
      "Calçados Online",
      "Lojatual E-Commerce",
      "Lazer & Vida",
      "MPOZENATO",
      "Lojas Clima",
      "Commerce Brasil",
      "Le Petit Marché",
      "Move Green",
      "Decor Capas",
      "Spank Store",
      "CASATEMA",
      "Pró Spin",
      "Beek Geek’s Stuff",
      "Gigantec",
      "Mobly",
      "Stuttgart Importadora",
      "Lelive Calçados",
      "VALEJET",
      "Foca Louca",
      "Joias Lulean",
      "Amochila",
      "Alexshoes",
      "NetChairs",
      "KD Pneus",
      "Boleana.com",
      "NETBABYS",
      "Marca Fácil e Vinela",
      "Mega Empório",
      "RM Adesivos",
      "Embalando Sonhos",
      "Câmeras de Segurança",
      "AVELISHOMEFEELINGS",
      "ANIMAFEST",
      "Barrocarte",
      "Bananafoto",
      "Clube do Malte",
      "2001 Video",
      "Tok de Conforto",
      "Ezzencia",
      "OZ! Organize",
      "Capinhas Shop",
      "Laffetto",
      "Universal Presentes",
      "Caçula de Pneus",
      "e-Lustre",
      "CJ Store",
      "Microservice",
      "Amigonauta",
      "Giuliana Home",
      "Doce Noite",
      "Grenadine",
      "Le Lingerie",
      "Palácio da Arte",
      "A Dama e o Cachorrinho",
      "New Light",
      "Wac Wac",
      "Tienda Design",
      "Flores Online",
      "Giuliana Flores",
      "Riffel",
      "iClothes",
      "Flexmetal ",
      "KSelect",
      "Elitize",
      "Grão de Gente",
      "Cinerama",
      "Livraria Cultura - NÃƒO USAR",
      "Blue Pack",
      "Matsumoto",
      "Wtoys",
      "HTS Latarias",
      "Empório Sorio",
      "Le Diamonds",
      "Mister Festas",
      "Tico Tica Bum",
      "Wishes",
      "Formafina",
      "Allodi",
      "Compre Óculos",
      "Mais Vendidos",
      "QG Airsoft",
      "Meu Puff Ecológico",
      "Kutiz beauté",
      "Gasnag",
      "Dieta Dukan ",
      "Lushe",
      "Titanis",
      "Maria Ditinha ",
      "Gran Natural",
      "Jardim do Vinho",
      "Rodeo West",
      "Central Cabos",
      "Controle Net",
      "X-Trendy Shop",
      "Adesix",
      "ElanTrade",
      "OEMShop",
      "Elementar",
      "Clube do Lar",
      "Ponto e Ponto",
      "Tecnoferramentas",
      "Rumo Autopeças",
      "Liberatti",
      "Cheiro de Música",
      "Ideal Ferramentas",
      "Leitz",
      "Fellowes",
      "Maria Pia Casa",
      "Cabeleza",
      "BandUP",
      "Kallan",
      "Bud Decor",
      "Mash",
      "Dog Loja",
      "GG Presentes",
      "Chic Mix",
      "Indústria das Cadeiras",
      "Loja Milenarte",
      "Famatecnoshop",
      "EletroPrinter",
      "DBestShop",
      "Tutty Free",
      "Mega Lua Kids",
      "Virtal",
      "Star Mobile",
      "Cabala Telecom",
      "Big Informática",
      "Starblock",
      "Mix Network",
      "Seu Enxoval",
      "BemFixa",
      "Selltoner",
      "Toner Vale",
      "Multi-Ar",
      "Print Loja",
      "Mundo Digi",
      "GLOBAL ELETRO",
      "Gabriella Calçados",
      "SUGGAR",
      "Habiltec",
      "RetrôMania",
      "Decore Home Center",
      "Bicimoto",
      "Mundomax",
      "PontoFrio Atacado ",
      "4BABiES",
      "Sony Loja Oficial",
      "Cirúrgica Express",
      "NextBike",
      "Estrela10",
      "Darwin6",
      "Imaginia",
      "Grande Eletro",
      "Doutor Mídia",
      "Fama Security",
      "Empório do Lazer",
      "Maxi Ferramentas",
      "MyNiCO",
      "Geração Pet",
      "Arsenal Car",
      "Icos",
      "JogaPlay",
      "Gurivéio",
      "Cestas Michelli",
      "Huble",
      "Homem da Terra",
      "Shock Games",
      "Redes de Dormir",
      "Don Abel",
      "Valdar Móveis",
      "X4 Adesivos",
      "Acessórios Motos",
      "On The Wall",
      "Starhouse",
      "Cissa Magazine",
      "King Beer",
      "UD Market",
      "Grudado",
      "ATP Store",
      "Reference",
      "Cirilo Cabos ",
      "DKWStore",
      "AIUP",
      "Intersolução",
      "Elare",
      "Vendas Rápidas",
      "Dr Lux",
      "Tapetes.com",
      "Pozelar",
      "Centauro",
      "MadeiraMadeira",
      "Emania",
      "Vinno",
      "Todovino",
      "Cigame",
      "SOS da Piscina",
      "Masada",
      "Compre Makeup",
      "BoaCoisa",
      "Punkt",
      "Box Marcas",
      "Camisaria Colombo",
      "Buettner",
      "Café Fácil",
      "Lefine",
      "Loja Positano",
      "E-cozinhas",
      "Biobike ",
      "WoufStore",
      "Dive Show",
      "Autourbano",
      "TETRIX",
      "The Men’s Store",
      "General Car",
      "Pontto Lavabo",
      "Rei da Oferta",
      "BestGamers",
      "Lagos & Cia",
      "Espartanos",
      "SunJohn",
      "About Home",
      "Fairmont",
      "SB Magazine",
      "Garmin",
      "PortCasa",
      "Doublju",
      "Disk Digitais",
      "Petvirtual",
      "Mundo do Lazer",
      "Color Me",
      "Nikkey",
      "TocTech",
      "GT Suplementos",
      "G-Locks",
      "IMAshop",
      "Joia em Casa",
      "Nano Labs",
      "Bijoulux",
      "Up2Games",
      "Centro Natural",
      "Big Stok",
      "Projeto Verão",
      "ALBA eletrônicos",
      "E-Salute",
      "Kin Bike",
      "Cachaça Shop",
      "França Games",
      "Tuning Parts",
      "ShopB",
      "Casa da Máquina",
      "LEP BIKES",
      "BringIT",
      "Tudo de Casa",
      "Tricae",
      "Treino e Corrida",
      "Divine Enxovais",
      "Pet Litoral",
      "MercuryShop",
      "Global Vision",
      "eFácil",
      "Vênus Decor",
      "Astro Distribuidora",
      "FLAWIL",
      "QUALLINUTRI",
      "Stormstrong",
      "Valdo Bike",
      "Atacadão do Lar",
      "Café Tramonti",
      "Boa Saúde Suplementos",
      "Boutique de Luxo",
      "Loja do Kite",
      "Car Fashion Capas",
      "WebContinental",
      "Laranja.com",
      "Ibitinga Enxoval",
      "SVC Laser",
      "Shopping Atual",
      "Marisa",
      "Relogios Oversized",
      "Orangebox Miniaturas",
      "FREE ITALIA",
      "Autoparts Online",
      "Mobile Maníacos",
      "CentralFit",
      "Mais Construção",
      "Festabox",
      "Camasoft",
      "BOM GOSTO ENXOVAIS",
      "MOBILISTORE",
      "LojasKD Móveis",
      "FBSHOP",
      "Matecki",
      "CDISCOUNT",
      "Aquarelaeletro",
      "Inova Esportes",
      "Biopoint",
      "Indieshop Castelão",
      "Zona Criativa",
      "Mundo Adora",
      "Músculos na Web",
      "FLORICULTURA CESTA E FLOR",
      "WEBMIC click, compre",
      "Ri Happy – Exclusivo Online",
      "Capital do Enxoval",
      "Safetron",
      "MaisQPneu",
      "GFC",
      "Kikos Fitness Store",
      "DLD STORE",
      "MAISGAME",
      "Organize Shop",
      "BELLA BRASIL DECOR",
      "Casa do Mecânico",
      "Trapemix",
      "Vinela",
      "CASALANDIA",
      "Oficina do Skate",
      "Aix Casa",
      "Makeda",
      "Loja Rede Social",
      "Mil Special Shop",
      "Youlet",
      "FUEL4FIT",
      "Cprz Tecnologia",
      "IMPRESS CARD",
      "netDECOR",
      "E-store",
      "Muito Balato",
      "ZLOJADETESTEZ3",
      "BD Net Imports",
      "RicardoACCDuplicated",
      "ZLOJADETESTEZ4",
      "LOJIX",
      "Segurança Mais",
      "Sublime Cosméticos",
      "Net System Shop",
      "YouWin",
      "Nutriva",
      "Loja do Alemão",
      "LOCTEK",
      "ZLOJADETESTEZ5",
      "Loja FREECS",
      "Teclacenter",
      "SHOPLOKO",
      "E-Maxma",
      "Heyne",
      "MISTER IMAGEM",
      "Unique For You",
      "Netelectro",
      "Casas Bahia - PraÃ§a Ramos ",
      "PontoFrio - Megastore",
      "PontoFrio - Shopping Center TaboÃ£o 2",
      "Casas Bahia - Shopping ABC",
      "Brilhar Strass",
      "STAR CAPACETES",
      "MODELLER PLUS",
      "G-FIRE Computadores",
      "W8 Acessórios",
      "4lifeStore",
      "Katy Calçados e Esportes",
      "Z7 Telecom",
      "LeVino",
      "Loja da Jardinagem",
      "LATIKA",
      "Móveis Unidos",
      "Gláucia Joias",
      "VIDEOFOTO",
      "Loja Casa Faz",
      "X5 COMPUTADORES",
      "Ejacaré",
      "Meu Perfume",
      "Well Store – Moda Urbana",
      "Mercado das Ferragens",
      "PLANETSHIRTS",
      "Venerare",
      "CDISCOUNT FRANCA",
      "Blitzart",
      "Taquilla",
      "SPA TURBO",
      "WCT FITNESS",
      "Lar Adesivos",
      "Tire Store",
      "SOMEWAY ",
      "Empório das Máquinas",
      "Rapina Imports",
      "SHOP DBS",
      "Onda Digital",
      "Juballee",
      "Estevam Eletro Magazine",
      "Collect4Fun",
      "HONEY BE",
      "Arclube",
      "NANÁ SPORTS",
      "Mycompras ",
      "Natuforma",
      "Blubelle",
      "PNEU FAST",
      "Empório Duda Batista",
      "Linara Banho",
      "Qloja!",
      "Guaraci Digital",
      "ADECIL.COM",
      "MeuAnel Joias",
      "Livraria da Vila",
      "ALIVET SAÚDE ANIMAL",
      "Gold Rose Flores e Presentes ",
      "Mania Virtual",
      "ARTEZANAL ",
      "Stirring Beauty",
      "JO Decor",
      "Pet Supply Home",
      "ILUNATO",
      "SOL Paragliders",
      "RMS Áudioevídeo",
      "De 1 Tudo Decor",
      "Club Eletro",
      "GTI Auto Parts",
      "DesignTime",
      "Centermobile",
      "TECHCLUBE",
      "Runna Bike",
      "Angela Magazine",
      "Sarcompy ",
      "MEGASOARES",
      "PlayPad",
      "RS1",
      "Essenza Reale Perfumes ",
      "Surfista de Trem",
      "LadyHair Profissional",
      "Zurich Imports",
      "Budin Ferramentas",
      "Itech",
      "Cirúrgica Médica",
      "ALL WANT STORE ",
      "Super Saudável ",
      "Netnails Unhas Online",
      "CenterSaúde",
      "Esportes Camisa 10",
      "RS Performance",
      "Bololô",
      "Wishhouse",
      "Colorsom",
      "BBBaterias",
      "Specialitá Lingerie",
      "VGSHOP ",
      "Canecas PontoCom",
      "KAISER BAAS",
      "NETALARMES",
      "PNEUX",
      "TREINAMENTO PRIME",
      "Maria Chapéu",
      "AGROSHOP",
      "Liveta Comércio",
      "TRAZPRACA",
      "POLOSURF",
      "Beleza de Mulher",
      "Netautomotive",
      "Bordon Casa",
      "AMS EVA",
      "Vizzent Calçados",
      "Premier Shop",
      "RADAR DETECTORS",
      "Livraria Trindade Gospel",
      "COMPRASEXPRESS",
      "UP 3D Brasil",
      "PetnaNet",
      "Tudo Forte",
      "Boomer Brinquedos",
      "Shop Noroeste",
      "ZTESTEBKLP1370",
      "Restaurante Shop",
      "Luxe4home",
      "Tenda Gospel",
      "Tri-Jóia Shop",
      "Tennis Classic",
      "TUDO JOIAS",
      "BESTPLUS",
      "Flaminga",
      "Zenithe Ferramentas",
      "Indomitum",
      "Muehlbauer Informática",
      "Casa das Impressoras ",
      "SB RIO",
      "TwoDogs",
      "Comprasom",
      "PONTO DAS MANGUEIRAS",
      "Bistrô da Beleza",
      "PLUS FERRAMENTAS",
      "MILANI SHOP MÓVEIS",
      "LOJA MABEL",
      "Start Nutrition",
      "belezacosmeticos",
      "RAFAELETRO",
      "VIVENDA LAZER",
      "Alphabox",
      "Boomerangue",
      "Toque de Joia",
      "LILLIPUT Brinquedos",
      "MARIETA MARTINS BOUTIQUE",
      "AZ Perfumes",
      "OPTICAHEMY",
      "MainShop",
      "Ferramix",
      "Japan Trade",
      "Aplique Adesivos",
      "Global Compras",
      "NOVA CONCURSOS",
      "Casa Klee",
      "Mais Vantagens",
      "NAILSMAGAZINE",
      "Lumus Online",
      "Beluni",
      "Santafina Little Luxuries ",
      "GLÜCK Acessórios",
      "KOALAELETROSHOP",
      "Shop4Men",
      "GigaBike",
      "LoveLetter",
      "Pili Pili Brinquedos Educativos",
      "MINI-ÍDOLOS",
      "Apollo Racing",
      "LGA COMÉRCIO LTDA",
      "Audiotec Computadores",
      "Janus Magazine",
      "MARTINELI FERRAMENTAS",
      "TODAMULHER",
      "CPAPMed",
      "INOVE CERTO",
      "Bob Zoom",
      "VCompra",
      "Ibyte",
      "Shopmultipratica",
      "Targus",
      "Casa Sua Beleza",
      "SóEletroMóveis",
      "Test Brasil",
      "VinikoLoja",
      "MONSTERSTOK",
      "VarieShop",
      "Carapirá Pesca ",
      "Silkn",
      "Flash Compras",
      "Costa Atacado ",
      "GuitiShop",
      "POISONCAR",
      "Pets na Moda",
      "Minha Ótica Online ",
      "Selah Produções",
      "Nine Led",
      "EFATHA",
      "BAZAR DOS COSMETICOS",
      "Shopinfo",
      "EDITORA ESTRONHO",
      "Opt Bolsas",
      "SKALLA MAGAZINE",
      "ÚTIL MAIS",
      "JCA",
      "Dedobrinquedo",
      "LAZULIE",
      "Meu Espelho",
      "Dermake",
      "TOTAL BUY",
      "Amiamo Accessori",
      "FONEFER",
      "ATS INFORMATICA",
      "ENTRE MAMAES",
      "Mainci",
      "Eletrogeno",
      "CALANGO MUSIC",
      "PICK UPS BRASIL",
      "BV MAGAZINE",
      "SUPLEMENTOS ZONE ",
      "iSold",
      "Super Criativos",
      "SABOR EM GRÃOS ",
      "FABRICA DE CARREGADOR",
      "Pneumarket",
      "Bebedouros e Cia",
      "Desk Tecnologia",
      "BIKE AND FITNESS",
      "50 + SAÚDE",
      "TINTAS AUTOMOTIVAS",
      "SUPER GADGETS ",
      "DALUEL",
      "Grupo Nato Eletro",
      "MM PARTS",
      "MATCHPOINT",
      "RAFCAR ACESSÓRIOS AUTOMOTIVOS",
      "TRICOLINHAS",
      "SJO ARTIGOS RELIGIOSOS",
      "ABMIDIA",
      "KRIBÊS CALÇADOS & ACESSÓRIOS",
      "Daskom",
      "Lojas Manica",
      "Itotal",
      "B&B Plásticos",
      "Smart Us Magazine",
      "Temperato – Design com Sabor",
      "MANCHESTER AUTOMAÇÃO COMERCIAL",
      "Luz Store",
      "Be Little",
      "Donaflor",
      "Setedodois",
      "Quero um Instrumento",
      "Cabana Sport",
      "SAARA BRASIL",
      "MixAuto Acessórios Automotivos",
      "Cherie Bijoux",
      "Ponto Telecom",
      "Selfshop Eletro",
      "GIFTCENTER",
      "ZTESTEBKLP1441",
      "Café Store",
      "ZOOVAREJODIGITAL",
      "Quality Suplementos",
      "HSPORTS",
      "Bolsas Relicário",
      "Americanas",
      "Submarino",
      "WallMart",
      "RicardoEletro"
    ];
    return stores[Math.floor(Math.random() * stores.length)];
  }
}
